// angular/tractor-store/projects/decide/src/shared/components/variant-option/variant-option.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  input,
} from '@angular/core';
import { NavigateToDirective } from '@internal/events';

@Component({
  selector: 'app-variant-option',
  imports: [NavigateToDirective],
  template: `
    <li class="d_VariantOption" [style.--variant-color]="color()">
      <i class="d_VariantOption__color"></i>
      @if (selected()) {
        <strong>{{ name() }}</strong>
      } @else {
        <a [navigateTo]="'decide.product'" [navParams]="linkParams()">{{ name() }}</a>
      }
    </li>
  `,
  styleUrl: './variant-option.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class VariantOption {
  readonly id = input.required<string>();
  readonly sku = input.required<string>();
  readonly name = input.required<string>();
  readonly color = input.required<string>();
  readonly selected = input<boolean>(false);

  readonly linkParams = computed(() => ({ id: this.id(), sku: this.sku() }));
}

// react/tractor-store/apps/decide/src/features/product/VariantOption.tsx
import type { CSSProperties } from 'react';
import { NavigateLink } from '@react-internal/navigation';
import { useScopedStyles } from '@react-internal/mfe-runtime';
import { variantOptionStyles } from './variant-option-styles';

interface Props {
  readonly id: string;
  readonly sku: string;
  readonly name: string;
  readonly color: string;
  readonly selected?: boolean;
}

export function VariantOption({ id, sku, name, color, selected = false }: Props) {
  useScopedStyles('decide-variant-option', variantOptionStyles);

  // CSS custom property — React types require the cast.
  const style = { '--variant-color': color } as CSSProperties;

  return (
    <li className="d_VariantOption" style={style}>
      <i className="d_VariantOption__color"></i>
      {selected ? (
        <strong>{name}</strong>
      ) : (
        <NavigateLink intent="decide.product" params={{ id, sku }}>
          {name}
        </NavigateLink>
      )}
    </li>
  );
}
