// angular/tractor-store/projects/checkout/src/shared/components/compact-header/compact-header.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  inject,
} from '@angular/core';
import { NavigateToDirective } from '@ng-internal/navigation';
import { ResourceService } from '../../utils/resource.service';

@Component({
  selector: 'app-compact-header',
  imports: [NavigateToDirective],
  template: `
    <div class="c_CompactHeader__inner">
      <a class="c_CompactHeader__link" [appNavigateTo]="'explore.home'">
        <img
          class="c_CompactHeader__logo"
          [src]="logoUrl"
          alt="Micro Frontends - Tractor Store"
        />
      </a>
    </div>
  `,
  styleUrl: './compact-header.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
  host: { class: 'c_CompactHeader', role: 'banner' },
})
export class CompactHeaderComponent {
  private readonly image = inject(ResourceService);
  readonly logoUrl = this.image.cdnUrl('/cdn/img/logo.svg');
}

// react/tractor-store/apps/checkout/src/features/checkout/CompactHeader.tsx
import { NavigateLink } from '@react-internal/navigation';
import { useScopedStyles } from '@react-internal/mfe-runtime';
import { useCdnBase } from '@react-internal/mfe-runtime';
import { cdnUrl } from '@react-internal/mfe-runtime';
import { compactHeaderStyles } from './compact-header-styles';

export function CompactHeader() {
  useScopedStyles('checkout-compact-header', compactHeaderStyles);
  const base = useCdnBase();

  return (
    <header className="c_CompactHeader" role="banner">
      <div className="c_CompactHeader__inner">
        <NavigateLink intent="explore.home" className="c_CompactHeader__link">
          <img
            className="c_CompactHeader__logo"
            src={cdnUrl('/cdn/img/logo.svg', base)}
            alt="Micro Frontends - Tractor Store"
          />
        </NavigateLink>
      </div>
    </header>
  );
}
