// react/tractor-store/apps/explore/src/features/category/Filter.tsx
import { NavigateLink, type NavTarget } from '@react-internal/navigation';
import { useScopedStyles } from '@react-internal/mfe-runtime';
import { filterStyles } from './filter-styles';

export interface FilterItem {
  readonly link: NavTarget;
  readonly name: string;
  readonly active: boolean;
}

export function Filter({ filters }: { filters: readonly FilterItem[] }) {
  useScopedStyles('explore-filter', filterStyles);
  return (
    <div className="e_Filter">
      Filter:
      <ul>
        {filters.map((f) =>
          f.active ? (
            <li key={f.name} className="e_Filter__filter--active">
              {f.name}
            </li>
          ) : (
            <li key={f.name}>
              <NavigateLink intent={f.link.intent} params={f.link.params ?? {}}>
                {f.name}
              </NavigateLink>
            </li>
          ),
        )}
      </ul>
    </div>
  );
}

// angular/tractor-store/projects/explore/src/shared/components/filter/filter.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  input,
} from '@angular/core';
import { NavigateToDirective, NavTarget } from '@internal/events';

export interface FilterItem {
  link: NavTarget;
  name: string;
  active: boolean;
}

@Component({
  selector: 'app-filter',
  imports: [NavigateToDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
  styleUrl: './filter.scss',
  template: `
    <div class="e_Filter">
      Filter:
      <ul>
        @for (f of filters(); track f.name) {
          @if (f.active) {
            <li class="e_Filter__filter--active">{{ f.name }}</li>
          } @else {
            <li><a [navigateTo]="f.link.intent" [navParams]="f.link.params ?? {}">{{ f.name }}</a></li>
          }
        }
      </ul>
    </div>
  `,
})
export class FilterComponent {
  readonly filters = input.required<FilterItem[]>();
}
