// react/tractor-store/apps/explore/src/features/category/ProductTile.tsx
import { NavigateLink } from '@internal/navigation';
import type { Product } from '../../api/categories';
import { useScopedStyles } from '@internal/mfe-runtime';
import { useCdnBase } from '@internal/mfe-runtime';
import { imgSrc, imgSrcset } from '@internal/mfe-runtime';
import { fmtPrice } from '@internal/mfe-runtime';
import { productTileStyles } from './product-tile-styles';

export function ProductTile({ product }: { product: Product }) {
  useScopedStyles('explore-product-tile', productTileStyles);
  const base = useCdnBase();

  return (
    <li className="e_Product">
      <NavigateLink
        intent={product.link.intent}
        params={product.link.params ?? {}}
        className="e_Product_link"
      >
        <img
          className="e_Product_image"
          src={imgSrc(product.image, 200, base)}
          srcSet={imgSrcset(product.image, [200, 400, 800], base)}
          sizes="300px"
          width={200}
          height={200}
          alt=""
        />
        <span className="e_Product_name">{product.name}</span>
        <span className="e_Product_price">{fmtPrice(product.startPrice)}</span>
      </NavigateLink>
    </li>
  );
}

// angular/tractor-store/projects/explore/src/shared/components/product-tile/product-tile.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
  computed,
  inject,
  input,
} from '@angular/core';
import { NavigateToDirective } from '@internal/events';
import type { ProductModel } from '../../../core/data/contracts/models/product.model';
import { ResourceService } from '../../utils/resource.service';
import { fmtPrice } from '../../utils/price';

@Component({
  selector: 'app-product-tile',
  imports: [NavigateToDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.ShadowDom,
  styleUrl: './product-tile.scss',
  template: `
    <li class="e_Product">
      <a class="e_Product_link" [navigateTo]="product().link.intent" [navParams]="product().link.params ?? {}">
        <img
          class="e_Product_image"
          [src]="imgSrc()"
          [srcset]="imgSrcset()"
          sizes="300px"
          width="200"
          height="200"
          alt=""
        />
        <span class="e_Product_name">{{ product().name }}</span>
        <span class="e_Product_price">{{ price() }}</span>
      </a>
    </li>
  `,
})
export class ProductTileComponent {
  private readonly image = inject(ResourceService);

  readonly product = input.required<ProductModel>();
  readonly imgSrc = computed(() => this.image.imgSrc(this.product().image, 200));
  readonly imgSrcset = computed(() =>
    this.image.imgSrcset(this.product().image, [200, 400, 800]),
  );
  readonly price = computed(() => fmtPrice(this.product().startPrice));
}
